export const AVAILABLE_FONTS = [
  'Inter',
  'Playfair Display',
  'Dancing Script',
  'Cinzel',
  'Cormorant Garamond',
  'Libre Baskerville',
  'Montserrat',
  'Oswald',
  'Pacifico',
  'Raleway',
  'Lora',
  'Merriweather',
  'Great Vibes',
  'Sacramento',
  'Arial',
  'Georgia',
  'Times New Roman',
  'Courier New',
  'Verdana',
];
