export const VECTOR_SHAPE_CATEGORIES = [
  {
    id: 'vs_stars',
    label: 'Stars',
    files: [
      'star_4pt_01.svg', 'star_4pt_02.svg', 'star_4pt_03.svg', 'star_4pt_04.svg', 'star_4pt_05.svg',
      'star_5pt_01.svg', 'star_5pt_02.svg', 'star_5pt_03.svg', 'star_5pt_04.svg',
      'star_6pt_01.svg', 'star_6pt_02.svg', 'star_6pt_03.svg', 'star_6pt_04.svg', 'star_6pt_05.svg', 'star_6pt_06.svg',
      'star_7pt_01.svg', 'star_7pt_02.svg', 'star_7pt_03.svg', 'star_7pt_04.svg',
      'star_8pt_01.svg', 'star_8pt_02.svg', 'star_8pt_03.svg', 'star_8pt_04.svg',
      'star_12pt_01.svg',
      'star_20pt_01.svg', 'star_20pt_02.svg',
      'star_30pt_01.svg', 'star_30pt_02.svg', 'star_30pt_03.svg',
    ],
  },
  {
    id: 'vs_arrows',
    label: 'Arrows',
    files: [
      'arrow_right_01.svg', 'arrow_right_02.svg',
      'arrow_up_01.svg', 'arrow_up_02.svg',
      'arrow_ribbon_03.svg', 'arrow_ribbon_04.svg',
    ],
  },
  {
    id: 'vs_rectangles',
    label: 'Rectangles & Squares',
    files: [
      'rectangle_wide_01.svg', 'rectangle_wide_02.svg',
      'roundedrec_01.svg', 'roundedrec_02.svg',
      'roundedrec_short_01.svg', 'roundedrec_short_02.svg',
      'square_01.svg', 'square_02.svg', 'square_03.svg', 'square_04.svg', 'square_05.svg', 'square_06.svg',
    ],
  },
  {
    id: 'vs_polygons',
    label: 'Polygons',
    files: [
      'diamond.svg',
      'pentagon.svg',
      'hexagon_01.svg', 'hexagon_02.svg',
      'octagon.svg',
      'trapezoid_01.svg', 'trapezoid_02.svg',
      'plus_01.svg', 'plus_02.svg',
    ],
  },
  {
    id: 'vs_icons',
    label: 'Icons & Symbols',
    files: [
      'heart_01.svg', 'heart_02.svg',
      'cloud_01.svg', 'cloud_2.svg',
      'flag_01.svg', 'flag_02.svg', 'flag_03.svg', 'flag_04.svg', 'flag_05.svg',
      'speech_bubble_01.svg', 'speech_bubble_02.svg',
      'map_marker_01.svg',
      'gear_01.svg',
      'eye_01.svg',
      'moon_crescent_01.svg',
      'spiral_01.svg',
      'music_note_01.svg',
    ],
  },
  {
    id: 'vs_rocks',
    label: 'Rocks & Geology',
    files: [
      'rock_jagged_01.svg', 'rock_jagged_02.svg',
      'rock_spiky_01.svg', 'rock_spiky_02.svg',
      'rock_bulbous_01.svg', 'rock_bulbous_02.svg',
      'rock_flat_01.svg', 'rock_flat_02.svg',
      'rock_tall_01.svg', 'rock_tall_02.svg',
      'rock_crater_01.svg',
      'rock_crystal_01.svg',
      'rock_boulder_01.svg', 'rock_boulder_02.svg',
      'rock_arch_01.svg', 'rock_arch_02.svg',
      'rock_mesa_01.svg',
      'rock_pillar_01.svg', 'rock_pillar_02.svg',
      'rock_stack_01.svg',
      'rock_slab_01.svg',
      'rock_volcanic_01.svg',
    ],
  },
  {
    id: 'vs_lobsters',
    label: 'Lobsters',
    files: [
      'lobster_glyph_01.svg', 'lobster_glyph_02.svg', 'lobster_glyph_03.svg',
      'lobster_glyph_04.svg', 'lobster_glyph_05.svg', 'lobster_glyph_06.svg',
      'lobster_glyph_07.svg', 'lobster_glyph_08.svg', 'lobster_glyph_09.svg',
      'lobster_glyph_10.svg', 'lobster_glyph_11.svg', 'lobster_glyph_12.svg',
      'lobster_claw_01.svg', 'lobster_claw_02.svg',
      'lobster_side_01.svg', 'lobster_side_02.svg',
      'lobster_king_01.svg',
      'lobster_tribal_01.svg',
    ],
  },
  {
    id: 'vs_undersea',
    label: 'Undersea',
    files: [
      'coral_branch_01.svg', 'coral_branch_02.svg',
      'coral_brain_01.svg',
      'coral_fan_01.svg',
      'seaweed_01.svg', 'seaweed_02.svg',
      'jellyfish_01.svg', 'jellyfish_02.svg',
      'fish_01.svg', 'fish_02.svg', 'fish_tropical_01.svg',
      'shell_01.svg', 'shell_02.svg', 'shell_spiral_01.svg',
      'seahorse_01.svg',
      'octopus_01.svg',
      'starfish_01.svg',
      'whale_01.svg',
      'turtle_01.svg',
      'crab_01.svg',
      'anchor_01.svg',
      'wave_01.svg',
      'bubble_cluster_01.svg',
    ],
  },
  {
    id: 'vs_metal',
    label: 'Metal & Fantasy',
    files: [
      'skull_01.svg',
      'skull_crossbones_01.svg',
      'lightning_01.svg', 'lightning_02.svg',
      'flame_01.svg', 'flame_02.svg',
      'sword_01.svg',
      'shield_01.svg',
      'crown_01.svg',
      'dragon_01.svg',
      'bat_01.svg',
      'trident_01.svg',
      'potion_01.svg',
      'axe_01.svg',
      'crystal_01.svg',
      'horn_01.svg',
    ],
  },
]
